### ISSUE TITLE
Website link broken?

### ISSUE THREAD

**Issue by g-simmons** [Farama-Foundation/chatarena#123]
https://www.chatarena.org/ doesn't seem to redirect to a site for this project

<img width="632" alt="image" src="https://github.com/Farama-Foundation/chatarena/assets/28633482/695da589-834e-4e35-ac10-eb2245403963">

**Comment by jkterry1** [comment]
Hey, thanks so much for bringing this to our attention! We're going to get another website set up that looks like the other Farama websites in the near future
