### ISSUE TITLE
Feature request: RL libraries integration

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/chatarena#14]
Hi, I was wondering if it would be possible to integrate chat arena with something like gymnasium or pettingzoo (multi agent version of gym). Would be very interesting to see LLMs be used both for language envs and for regular envs like poker, connect four etc.

**Comment by jimmycode** [comment]
Thank you for the feature request. At the moment (Apr 2023) ChatArena dev team focuses on providing a diverse set of language game environments and LLM backends. Since our abstraction and APIs are similar with gymnasium or pettingzoo, theoretically users could use their favourite RL libraries to train their models in ChatArena (for example, use the `Arena.save_history` method to export the game rollout for offline RL).

We welcome community contribution to support RL libraries integration :)

**Comment by elliottower** [comment]
> Thanks for offering contribution! I agree that it would be really powerful if users can do RL training with ChatArena. But I think it is also a good idea to decouple environment and RL frameworks, so that everyone can use their favourite RL library (CleanRL, Tianshou, RLlib, etc.) or their own RL implementation.
> 
> Maybe one _first step_ is to provide a notebook or tutorial (like [this one from pettingzoo](https://pettingzoo.farama.org/tutorials/cleanrl/implementing_PPO/)) to show case how to use the environment with other RL packages. For further integration, wrapper may be a good idea.

Makes sense. To create a tutorial like that would require a wrapper class to adapt the API to match but I can see how that would be nice to show with a full example so users can get the most out of it. Would there be any interest in a conversation wrapper being included for this library in [Shimmy](https://shimmy.farama.org/)? We have made wrappers for popular external RL envs like deepmind control, would love to have another multi agent env and such a unique use case. But maybe it would be more ideal to integrate directly in this codebase with a PR so that integration/tutorials could be tested and backwards compatibility can be preserved. We don’t currently offer training tutorials on Shimmy either so that would need to be on this repository.

**Comment by jimmycode** [comment]
Both having a wrapper in Shimmy and integrating into this codebase with a PR make perfect sense. The latter would offer better backward compatibility, and since we are planning to add more environments to the library, we have more interest in the latter. But if you find writing a wrapper for this library in Shimmy easier, we encourage you to go for it. :)

**Comment by elliottower** [comment]
Is this already being worked on internally? I saw an example using pettingzoo chess but don’t see pettingzoo or gymnasium appearing anywhere in the repo. 

If it’s not being done already I’d love to help out, I was wondering if there’s a development discord or slack? Otherwise I can put questions here. Would like to make sure I’m implementing it in a way that makes sense to you guys. 

Apologies for the delay, I’ve been working on releases for other libraries the last few weeks.

**Comment by yuxiang-wu** [comment]
Thank you for getting back!

- Regarding the first question: We ported the chess environment from Pettingzoo here: https://github.com/chatarena/chatarena/blob/main/chatarena/environments/pettingzoo_chess.py
- We created a slack channel here: https://join.slack.com/t/chatarena/shared_invite/zt-1t5fpbiep-CbKucEHdJ5YeDLEpKWxDOg

I am happy to discuss here or in slack for push forward the development in this direction.

**Comment by elliottower** [comment]
Finally got a chance to look through the code to see how difficult it would be to make a PettingZoo wrapper around an entire Chat Arena environment (making a general utility to load pettingzoo or for example openspiel text board game environments into chat arena would be very fruitful as well—letting LLMs play battleship or simple poker, etc). 

It looks like the step() calls are very similar, the messages could be included in the observations, and backends and configs could be environment parameters. The parallel ticker on the huggingface demo seems very similar to the parallel environment type we have in pettingzoo as well. And the handling of agents could definitely be done with pettingzoo as well. Gymnasium has a text action/observation space type which can be used for any length sequence like are used in the messages, so I think everything should be possible. 

The codebase could be refactored to use PettingZoo as a framework to handle the different agents, but I don’t want to start working on that before getting confirmation, as obviously it would be a sizable code modification. Alternatively, a wrapper could be written first which makes it compatible using the same underlying codebase as is currently used.

**Comment by elliottower** [comment]
I’m also curious if there are any plans to add langchain support as a backend, to allow users to build on top of models and test more complex chat bots for example.
