### ISSUE TITLE
Support Langchain Agents

### ISSUE THREAD

**Issue by Div99** [Farama-Foundation/chatarena#23]
Hi, will love to try out chatarena with the feature to simply import any existing Langchain agents

**Comment by yuxiang-wu** [comment]
Apologies for the delay. We are planning to support langchain backend. We will announce our development roadmap this week. Join our slack channel to stay tuned: https://join.slack.com/t/chatarena/shared_invite/zt-1t5fpbiep-CbKucEHdJ5YeDLEpKWxDOg

**Comment by elliottower** [comment]
I believe this was solved in https://github.com/Farama-Foundation/chatarena/pull/46 but if not feel free to reopen or comment here
