### ISSUE TITLE
Fix OpenAI errors 

### ISSUE THREAD

**Issue by krrishdholakia** [Farama-Foundation/chatarena#51]
Hi @yuxiang-wu, 

Tried to do something similar and hit a ton of OpenAI errors (Context window limitations, rate limiting with gpt-4, etc.). 

Would recommend using something like `reliableGPT` for error handling - it'll do retries/model switching/etc. for you

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by elliottower** [comment]
Could you give specific OpenAI errors you are getting? Saw your other issue and am fine with adding a new backend for litellm if you'd like to create it (assuming that would also encompass GPT but I see reliableGPT is the same org as the other repo so maybe they serve different purposes). 

My inclination is just to hard code the openai version or do simple updates to make it work, having extra dependencies isn't ideal

**Comment by elliottower** [comment]
Tested locally with my API key and did encounter some OpenAI errors for sure but not sure exactly what the problems are, even with an older version of the library. I think I'd be okay with using reliableGPT if you're able to make a PR, as I don't know really how to fix this currently.
