### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by jas-ho** [Farama-Foundation/chatarena#53]
When doing 
`pip install -e .[all]` on the `dev` branch  (it's the same on `main` iirc) I get 
```
ERROR: Cannot install chatarena[all]==0.1.12.6 and pettingzoo[classic]==1.23.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    chatarena[all] 0.1.12.6 depends on chess==1.9.4; extra == "all"
    pettingzoo[classic] 1.23.1 depends on chess==1.7.0; extra == "classic"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by elliottower** [comment]
We’re about to release a new pettingzoo version and update chess but I’m not sure why this repo hard codes that chess version. @yuxiang-wu did this get done on purpose or was it just the version you happened to have installed or something?

**Comment by jas-ho** [comment]
thanks for answering!  if it's fixed by an upcoming pettingzoo release anyways then that's good enough imo

**Comment by elliottower** [comment]
This was fixed in PettingZoo 1.24.0, but ChatArena needs to be updated to use the latest version

**Comment by elliottower** [comment]
Posting this here as it's related, but the setup.py and pyproject.toml files are not matching and make each other redundant, both require the same extras but in pyproject I believe I removed the chess requirement but didn't do it in setup.py ( https://github.com/chatarena/chatarena/blob/fa6b374bb62fa7070454962eec6a9c88bc584d63)  It looks like there's some custom logic used in setup to remove duplicate requirements and such, so maybe it's best to keep the requirements in setup.py and use pyproject for metadata and setup? I can do this in the future and clean things up but don't have time currently/setup.py#L25)

**Comment by elliottower** [comment]
This has been fixed as well
