### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by krrishdholakia** [Farama-Foundation/chatarena#60]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/chatarena/chatarena/blob/fa6b374bb62fa7070454962eec6a9c88bc584d63/chatarena/backends/anthropic.py#L41

Would love to know if this might help - https://github.com/BerriAI/litellm

~100 lines of code, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by krrishdholakia** [comment]
cc: @ZhengyaoJiang

**Comment by elliottower** [comment]
cc comments in https://github.com/Farama-Foundation/chatarena/pull/62
