### ISSUE TITLE
got a "TypeError: Tab.__init__() got an unexpected keyword argument 'visible'" when perform 'gradio app'

### ISSUE THREAD

**Issue by HuXinjing** [Farama-Foundation/chatarena#74]
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/jason/codes/chatarena/app.py:124 in <module>                           │
│                                                                              │
│   121 │   │                                                                  │
│   122 │   │   with gr.Row():                                                 │
│   123 │   │   │   with gr.Column(elem_id="col-chatbox"):                     │
│ ❱ 124 │   │   │   │   with gr.Tab("All", visible=True):                      │
│   125 │   │   │   │   │   chatbot = gr.Chatbot(elem_id="chatbox", visible=Tr │
│   126 │   │   │   │                                                          │
│   127 │   │   │   │   player_chatbots = []                                   │
│                                                                              │
│ /home/jason/anaconda3/lib/python3.11/site-packages/gradio/component_meta.py: │
│ 146 in wrapper                                                               │
│                                                                              │
│   143 │   │   if in_event_listener():                                        │
│   144 │   │   │   return None                                                │
│   145 │   │   else:                                                          │
│ ❱ 146 │   │   │   return fn(self, **kwargs)                                  │
│   147 │                                                                      │
│   148 │   return wrapper                                                     │
│   149                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: Tab.__init__() got an unexpected keyword argument 'visible'

Does it mean a incorrect version of gradio which is 4.1.1 was installed?

**Comment by elliottower** [comment]
My guess is the api changed slightly, maybe try installing older versions of gradio? Otherwise in their release notes there should probably be something at some point mentioning this attribute being removed

**Comment by HuXinjing** [comment]
> My guess is the api changed slightly, maybe try installing older versions of gradio? Otherwise in their release notes there should probably be something at some point mentioning this attribute being removed (and how to fix it)

thx, it spins well after I downgrad the version of gradio
